name: pesel
description: Dart package for validation of the national identification number used in Poland.
version: 1.0.0
repository: https://github.com/rozpo/pesel

environment:
  sdk: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
